SecretShareAjax/config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    resources :friendships, :only => [:create] do
      collection do
        delete :destroy
      end
    end
  end
  resources :secrets, :only => [:create]
  resource :session, :only => [:create, :destroy, :new]

end

SecretShareAjax/app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :out_friend_id, :in_friend_id

  validates :out_friend_id, :in_friend_id, presence: true

  belongs_to(
  :added_friend,
  class_name: "User",
  foreign_key: :out_friend_id,
  primary_key: :id
  )

  belongs_to(
  :owner,
  class_name: "User",
  foreign_key: :in_friend_id,
  primary_key: :id
  )

  def self.can_friend?( current_user, other_user )
    (current_user.id != other_user.id ) && !(Friendship.exists?(:out_friend_id => other_user.id, :in_friend_id => current_user.id))
  end

  def self.can_unfriend?( current_user, other_user )
    Friendship.exists?(:out_friend_id => other_user.id, :in_friend_id => current_user.id)
  end
end

SecretShareAjax/app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :recipient_id, :sender_id, :body

  belongs_to(
  :recipient,
  class_name: "User",
  foreign_key: :recipient_id,
  primary_key: :id
  )

  belongs_to(
  :sender,
  class_name: "User",
  foreign_key: :sender_id,
  primary_key: :id
  )

  has_many(
  :secret_taggings,
  class_name: "SecretTagging",
  foreign_key: :secret_id,
  primary_key: :id
  )

  has_many :tags, :through => :secret_taggings, source: :tag


end

SecretShareAjax/app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :tag_id, :secret_id

  belongs_to(
  :tag,
  class_name: "Tag",
  foreign_key: :tag_id,
  primary_key: :id
  )

  belongs_to(
  :secret,
  class_name: "Secret",
  foreign_key: :secret_id,
  primary_key: :id
  )

end

SecretShareAjax/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :body

  has_many(
  :secret_taggings,
  class_name: "SecretTagging",
  foreign_key: :tag_id,
  primary_key: :id
  )

  has_many :secrets, :through => :secret_tagging, source: :secret

end

SecretShareAjax/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :sender_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many(
  :forced_friendships,
  class_name: "Friendship",
  foreign_key: :out_friend_id,
  primary_key: :id
  )

  has_many(
  :owned_friendships,
  class_name: "Friendship",
  foreign_key: :in_friend_id,
  primary_key: :id
  )


  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

SecretShareAjax/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

SecretShareAjax/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    sleep(1)
    @friendship = Friendship.new(in_friend_id: current_user.id, out_friend_id: params[:user_id])
    if @friendship.save
      render :json => @friendship
    else
      render :json => "Can not add friendship!"
    end
  end

  def destroy
    Friendship.find_by_in_friend_id_and_out_friend_id(current_user.id, params[:user_id]).destroy
    # respond_to do |format|
#       format.html { redirect_to users_url }
#       format.json { render :json => @something }
#     end
    render :json => {}, status: 200
    #head :ok
  end

end

SecretShareAjax/app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

  def new

  end

  def create
    @secret = Secret.new(params[:secret])
    @secret.sender_id = current_user.id
    if @secret.save
      render :json => @secret
    else
      render :json => "Can not save secret!"
    end
  end
end

SecretShareAjax/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

SecretShareAjax/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    @tags = Tag.all
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def index
    @users = User.all
    render :index
  end
end

SecretShareAjax/app/helpers/application_helper.rb
module ApplicationHelper
end

SecretShareAjax/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

SecretShareAjax/app/helpers/secrets_helper.rb
module SecretsHelper
end

SecretShareAjax/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

SecretShareAjax/app/helpers/users_helper.rb
module UsersHelper
end

SecretShareAjax/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
<%= current_user.username %>
<%= button_to "Log Out", session_url, method: :delete %>
<% else %>
<%= link_to "Log In", new_session_url %>
<%= link_to "Sign Up", new_user_url %>
<% end %>
<%= yield %>

</body>
</html>

SecretShareAjax/app/views/secrets/new.html.erb
<%= render "form" %>

SecretShareAjax/app/views/users/_form.html.erb
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_username">Enter Username</label>
  <input type="text" id="user_username" name="user[username]">

  <label for="user_password">Enter Password</label>
  <input type="text" id="user_password" name="user[password]">

  <input type="submit" value="Create Account">
</form>

SecretShareAjax/app/views/users/_index_partial.html.erb
<% @users.each do |user| %>
Username: <%= user.username %>
  <% if Friendship.can_friend?( current_user, user) %>
    <%= button_to "Friend!", user_friendships_url(user), method: :post %>
  <% end  %><br>

<% end %>

SecretShareAjax/app/views/users/_secrets_form.html.erb
<form id="secret-form">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <label for="secret_text">Secret Text!</label>
  <input type="text" id="secret_text" name="secret[body]">
  <input type="hidden" name="secret[recipient_id]" value="<%= params[:id] %>">



  <div>
    <%= render 'tags_partial' %>
  </div>
  <button id="more_tags">Add Another Tag</button>


  <input type="submit" value="Submit">

</form>

<script>
$('#more_tags').on("click", function(event) {
  event.preventDefault();
  console.log($('#tagHTML').html())
  $('#secret-form > div').append($('#tagHTML').html())
})
</script>

SecretShareAjax/app/views/users/_tags_partial.html.erb
<div id="tagHTML">
<select name="secret[tags]" id="secret_tags">
  <% @tags.each do |tag| %>
    <option value="<%= tag.id %>"><%= tag.body %></option>
<% end %></select>
</div>

SecretShareAjax/app/views/users/index.html.erb
<h2>Index!</h2>

<%= stylesheet_link_tag    :all %>
<div>
<% @users.each do |user| %>
Username: <%= user.username %>
<span class="friend-buttons <%= Friendship.can_friend?(current_user, user) ? "can-friend" : "can-unfriend" %>">

   <button class="friend" data-id="<%= user.id %>">heeey</button>

   <% can_unfriend = Friendship.can_unfriend?( current_user, user) %>
   <button class="unfriend"
     data-id="<%= user.id %>">unfriend!</button><br>
   </span>
<% end %>
</div>



<script>
var toggleFriendButtons = function($el) {
  $el.toggleClass("can-friend")
  $el.toggleClass("can-unfriend")
}

$('div').on("click", ".friend", function(event) {
  var $friend = $(event.currentTarget);
  var friendId = parseInt($friend.attr("data-id"));

  $friend.attr("disabled", "disabled");
  $friend.html("friending...")


  $.ajax({
   url: '/users/' + friendId + '/friendships',
   type: 'POST',
   dataType: 'json',
   success: function( resp ) {
     toggleFriendButtons($friend.parent())
     $friend.removeAttr("disabled");
     $friend.html("heeey")
   },
   error: function( req, status, err ) {
     $friend.removeAttr("disabled");
     $friend.html("heeey")
     alert( 'something went wrong: ' + status + err );
   }
  });
})

$('div').on("click", ".unfriend", function(event) {
  var $friend = $(event.currentTarget);
  var friendId = parseInt($friend.attr("data-id"));
  $friend.attr("disabled", "disabled");
  $friend.html("unfriending...")
  $.ajax({
   url: '/users/' + friendId + '/friendships',
   type: 'DELETE',
   dataType: 'json',
   success: function( resp ) {
     toggleFriendButtons($friend.parent())
     $friend.removeAttr("disabled");
     $friend.html("unfriend!")
   },
   error: function( req, status, err ) {
     $friend.removeAttr("disabled");
     $friend.html("unfriend!")
     alert( 'something went wrong: ' + status + err );
   }
  });
})



</script>

SecretShareAjax/app/views/users/new.html.erb
<h2>Sign up!</h2>

<%= render 'form' %>

SecretShareAjax/app/views/users/show.html.erb
<%= @user.username %>


<h2>Received Secrets!</h2>
<ul>
<% @user.received_secrets.each do |secret| %>
<li>From: <%= secret.sender.username %><br>
  Tags: <% secret.tags.each do |tag| %>
   <%= tag.body %>
   <%end%><br>
Secret: <%= secret.body %></li><br>
<%end%><br>
<br>
</ul>
<%= render "secrets_form" %>

<script>
$('#secret-form').on("submit", function(event) {
  event.preventDefault();

  var formData = $(this).serializeJSON();
  console.log(formData)
  // var $secretpost = $(event.currentTarget).parent();
//   // console.log($secretpost.find("#secret_recipient_id").val());
//   var recipientId = parseInt($secretpost.find("#secret_recipient_id").val());
//   var secretBody = parseInt($secretpost.find("#secret_text").val());
  $.ajax({
   url: '/secrets',
   type: 'POST',
   data: formData,
   success: function( resp ) {
     var newSecret = $('<li></li>');
     newSecret.append("Secret: " + resp.body);
     $('ul').append(newSecret);
     $('#secret_text').val('');
   },
   error: function( req, status, err ) {
     console.log(req)
     alert( 'something went wrong: ' + status + err );
   }
  });
})
</script>